---
title: "WordPredAlgo"
author: "Martin Skarzynski"
date: "March 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load preprocessed data
```{r}
uni<-read.csv("uni.csv")
bi<-read.csv("bi.csv")
tri<-read.csv("tri.csv")
quad<-read.csv("quad.csv")
penta<-read.csv("penta.csv")
hexa<-read.csv("hexa.csv")
hepta<-read.csv("hepta.csv")
```
## Split ngrams into n-1grams and last words

```{r}

bi$Word<-as.character(bi$Word)
bi2 <- do.call(rbind, strsplit(bi$Word, split = " "))
bi3 <- cbind(bi2[, 1], bi2[, 2])
colnames(bi3)<-c("biMinus1","NextWord")


tri$Word<-as.character(tri$Word)
tri2 <- do.call(rbind, strsplit(tri$Word, split = " "))
tri3 <- cbind(apply(tri2[, 1:2], 1, function(x) paste(x, collapse = " ")),
                  tri2[, 3])
colnames(tri3)<-c("triMinus1","NextWord")

quad$Word<-as.character(quad$Word)
quad2 <- do.call(rbind, strsplit(quad$Word, split = " "))
quad3 <- cbind(apply(quad2[, 1:3], 1, function(x) paste(x, collapse = " ")),
                  quad2[, 4])
colnames(quad3)<-c("quadMinus1","NextWord")

penta$Word<-as.character(penta$Word)
penta2 <- do.call(rbind, strsplit(penta$Word, split = " "))
penta3 <- cbind(apply(penta2[, 1:4], 1, function(x) paste(x, collapse = " ")),
                  penta2[, 5])
colnames(penta3)<-c("pentaMinus1","NextWord")

hexa$Word<-as.character(hexa$Word)
hexa2 <- do.call(rbind, strsplit(hexa$Word, split = " "))
hexa3 <- cbind(apply(hexa2[, 1:5], 1, function(x) paste(x, collapse = " ")),
                  hexa2[, 6])
colnames(hexa3)<-c("hexaMinus1","NextWord")

hepta$Word<-as.character(hepta$Word)
hepta2 <- do.call(rbind, strsplit(hepta$Word, split = " "))
hepta3 <- cbind(apply(hepta2[, 1:6], 1, function(x) paste(x, collapse = " ")),
                  hepta2[, 7])
colnames(hepta3)<-c("heptaMinus1","NextWord")

```

```{r}

```


```{r}

df7<-as.data.frame(hepta3)
df6<-as.data.frame(hexa3)
df5<-as.data.frame(penta3)
df4<-as.data.frame(quad3)
df3<-as.data.frame(tri3)
df2<-as.data.frame(bi3)
df1<-as.data.frame(uni$Word)

conv2char <- function(x) data.frame(lapply(x, as.character), stringsAsFactors=FALSE)

df1<-conv2char(df1)
df2<-conv2char(df2)
df3<-conv2char(df3)
df4<-conv2char(df4)
df5<-conv2char(df5)
df6<-conv2char(df6)
df7<-conv2char(df7)

splitInput <- unlist(strsplit("at the end of the", split = " "))
paste(tail(splitInput, 4), collapse = " ")

class(df3$triMinus1)
colnames(df1)<- "Word"
object.size(df5)
predictNgram <- function(input, df1, df2, df3, df4, df5) {
      input <- stripWhitespace(removePunctuation(tolower(input)))
      splitInput <- unlist(strsplit(input, split = " "))

      if (length(splitInput) > 4){
            input2 <- paste(tail(splitInput, 4), collapse = " ")
      } else {
            input2 <- paste(splitInput, collapse = " ")
      }
      pentaPred <- head(df5[which(df5$pentaMinus1 == input2),]$NextWord, 10)
      if (length(pentaPred > 0)){
            print("I was able to match the last five words")
            return(pentaPred)
      } else {            
      
      if (length(splitInput) > 3){
            input2 <- paste(tail(splitInput, 3), collapse = " ")
      } else {
            input2 <- paste(splitInput, collapse = " ")
      }
      quadPred <- head(df4[which(df4$quadMinus1 == input2),]$NextWord, 10)
      if (length(quadPred > 0)){
            print("I was able to match the last four words")
            return(quadPred)
      } else {      
      
      if (length(splitInput) > 2){
            input2 <- paste(tail(splitInput, 2), collapse = " ")
      } else {
            input2 <- paste(splitInput, collapse = " ")
      }
      triPred <- head(df3[which(df3$triMinus1 == input2),]$NextWord, 10)
      if (length(triPred > 0)){
            print("I was able to match the last three words")
            return(triPred)
      } else {
            input2 <- tail(splitInput, 1)
            biPred <- head(df2[which(df2$biMinus1 == input2),]$NextWord, 10)
      if (length(biPred) > 0){
            print("I was able to match the last two words")
            return(biPred)
      } else {
            uniPred <- head(uni$Word, 10)
            if (length(uniPred) > 0){
            print("I was not able to find a match, but here are some common words")
            return(uniPred)
            }
          }
      }
    }
  }
}
predictNgram("at the end of the", df1, df2, df3, df4, df5)

```



